name: Build & Deploy

on:
  push:
    branches:
      - main
      - run-unit-tests-cicd

jobs:
  terraform_deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Create artifacts directory
      run: mkdir -p ./artifacts

    - name: Install node dependencies
      run: npm install

    - name: Compile typescript
      run: npm run compile

    - name: Run unit tests
      run: npm run test:unit

    # - name: Clean and install prod node dependencies
    #   run: rm -rf node_modules && npm install --prod

    # - name: Prepare files to be Zipped
    #   run: rm -rf zipme && mkdir zipme && cp -r dist/src zipme && cp -r node_modules zipme

    # - name: Zip files
    #   run: zip -qq -r ../artifacts/spotify-api.zip ./*
    #   working-directory: ./zipme

    # - name: Verify Terraform version
    #   run: terraform --version

    # - name: Terraform init
    #   working-directory: ./terraform
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: terraform init -input=false

    # - name: Terraform validation
    #   run: terraform validate
    #   working-directory: ./terraform

    # - name: Terraform apply
    #   working-directory: ./terraform
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: terraform apply -auto-approve -input=false