name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1

    - name: Create artifacts directory
      run: mkdir -p ./artifacts/${{ github.repository }}

    # - name: Create Zip File
    #   uses: montudor/action-zip@v0.1.0
    #   with:
    #   args: zip -r ./artifacts/${{ github.repository }}/${{ github.sha }}.zip ./src


    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -input=false
      working-directory: ./terraform

    - name: Terraform validation
      run: terraform validate
      working-directory: ./terraform

    # - name: Terraform apply
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   run: terraform apply -auto-approve -input=false